<a href="https://colab.research.google.com/github/ihmkusuma/machine-learning-assignment-ilham-kusuma-4222311030/blob/main/machine_learning_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice & Assignment 1 — RE603: Machine Learning**

### Ilham Kusuma | 4222311030 | 6A Pagi Teknik Rekayasa Robotika

**Hands On Assignments**
1. Data Types pada Python
2. Function pada Python
3. OOP Principles (Encapsulation, Inheritance, Polymorphism)
4. OOP Paradigm (Constructors)

**Data Types (Hands On – Tuple)**

In [3]:
lokasi = (12.5, -7.8, 100.2)

print("Koordinat awal:", lokasi)

Koordinat awal: (12.5, -7.8, 100.2)


In [4]:
lokasi[0] = 15.0  # Apakah ini berhasil?

TypeError: 'tuple' object does not support item assignment

1. Program Pertama: Inisialisasi Tuple
Pada bagian ini, kode berjalan dengan sukses tanpa ada kendala.


* Apa yang terjadi: Kamu membuat sebuah variabel bernama lokasi yang berisi sekumpulan angka dalam tanda kurung (). Di Python, ini disebut sebagai Tuple.
* Baris Kode: lokasi = (12.5, -7.8, 100.2)
* Hasil: Program berhasil mencetak koordinat tersebut ke layar. Tuple sangat bagus digunakan untuk data yang seharusnya tidak berubah, seperti koordinat geografis atau nilai konstanta.

2. Program Kedua: Error Saat Mencoba Mengubah Data
Di sinilah muncul pesan kesalahan berwarna merah (TypeError).
* Apa yang terjadi: Kamu mencoba mengubah nilai pertama di dalam lokasi (indeks ke-0) dari 12.5 menjadi 15.0.
* Penyebab Error: Muncul pesan 'tuple' object does not support item assignment. Ini terjadi karena Tuple bersifat immutable, artinya setelah dibuat, isinya "dikunci" dan tidak bisa diganti, ditambah, atau dihapus.
* Analogi: Bayangkan Tuple seperti surat yang sudah ditulis dengan pulpen permanen; kamu tidak bisa menghapus satu kata dan menggantinya dengan kata lain.


**Data Types (Hands On – Set)**

In [5]:
id_pengguna = {101, 202, 303, 404}

print("Sebelum ditambah:", id_pengguna)

Sebelum ditambah: {202, 404, 101, 303}


Jika saya ingin menambahkan
1. id_pengguna.add(505) dan
2. id_pengguna.add(101) apa yang terjadi?



In [6]:
id_pengguna.add(505)
print("Setelah ditambah:", id_pengguna)

Setelah ditambah: {101, 202, 303, 404, 505}


In [7]:
id_pengguna.add(101)
print("Setelah ditambah:", id_pengguna)

Setelah ditambah: {101, 202, 303, 404, 505}


1. Menambahkan 505 (id_pengguna.add(505))
Apa yang terjadi: Nilai 505 belum ada di dalam himpunan (set) id_pengguna.
* Hasilnya: Python berhasil memasukkan nilai tersebut ke dalam set.
* Lihat Outputnya: Setelah perintah dijalankan, nilai 505 kini muncul di dalam kurung kurawal {101, 202, 303, 404, 505}.

2. Menambahkan 101 (id_pengguna.add(101))
Apa yang terjadi: Nilai 101 sudah ada sebelumnya di dalam set tersebut.
* Hasilnya: Python tidak memberikan pesan error, tetapi ia juga tidak menambahkannya lagi.
* Mengapa demikian? Karena sifat utama Set adalah unik. Setiap elemen hanya boleh muncul satu kali.
* Lihat Outputnya: Hasil cetak menunjukkan isi set tetap sama seperti sebelumnya, tidak ada angka 101 tambahan.

**Function (Hands-On)**

In [8]:
def nama_function():
    print("Hello, ini function pertamaku")

#Untuk menjalankan function, cukup panggil namanya
nama_function()

Hello, ini function pertamaku


**Function dengan Parameter**

Parameter ditentukan setelah nama fungsi, di dalam tanda kurung. Kita dapat menambahkan perintah sebanyak yang kita inginkan, cukup pisahkan dengan koma.

In [12]:
def sapa(nama):
    print(f"Halo, Kusuma! Ada yang bisa dibantu?")

sapa("nama")

Halo, Kusuma! Ada yang bisa dibantu?


Jika saya ingin membuat nama "Felda Ramadhan" Bagaimana cara untuk melengkapi program dibawah ini ?

In [13]:
def sapa(nama):
    print("Halo, Felda Ramadhan! Lihatlah program function pertamaku!")

sapa("nama")

Halo, Felda Ramadhan! Lihatlah program function pertamaku!


**Function dengan Banyak Parameter (Arbitrary Arguments) (Hands On)**

Buatlah fungsi untuk mencari "***Luas Lingkaran dan Keliling Lingkaran***" dengan jari-jari 15 cm.

1. Luas Lingkaran = 3.14 * jari-jari**2
2. keliling Lingkaran = 2 * 3.14 * jari-jari

In [22]:
# Function untuk menghitung luas lingkaran
def luas_lingkaran(r):
    luas = 3.14 * r**2
    return luas
# Function untuk menghitung keliling lingkaran
def keliling_lingkaran(r):
    keliling = 2 * 3.14 * r
    return keliling

print(luas_lingkaran(15))
print(keliling_lingkaran(15))

706.5
94.2


* luas_lingkaran(r) — fungsi menerima parameter r (jari-jari), lalu menghitung 3.14 * r²
* keliling_lingkaran(r) — fungsi menerima parameter r, lalu menghitung 2 * 3.14 * r
* Kedua fungsi dipanggil dengan nilai 15 sesuai soal

**Parameterized Constructor (Hands On)**

Buat suatu kelas bernama User

In [5]:
# Membuat kelas User
class User:
    def __init__(self, username, email, umur):
        self.username = username
        self.email = email
        self.umur = umur

    def info_user(self):
        return (
            f"Username : {self.username}\n"
            f"Email    : {self.email}\n"
            f"Umur     : {self.umur} tahun"
        )

# Membuat objek dari kelas User
user1 = User("Kusuma", "ksa23batam@gmail.com", 23)

# Menampilkan informasi pengguna
print(user1.info_user())

Username : Kusuma
Email    : ksa23batam@gmail.com
Umur     : 23 tahun


**Instance Variable (Hands On)**

Buatlah class Lingkaran yang memiliki atribut : jari-jari 10 cm, pi = 3.14159
dengan method Luas Lingkaran dan Keliling Lingkaran

In [6]:
class Lingkaran:
    def __init__(self, jari_jari):
        self.jari_jari = jari_jari
        self.pi = 3.14159

    def luas(self):
        return self.pi * self.jari_jari ** 2

    def keliling(self):
        return 2 * self.pi * self.jari_jari


# Membuat objek dari kelas Lingkaran
lingkaran1 = Lingkaran(10)

# Menampilkan hasil
print(f"Jari-jari  : {lingkaran1.jari_jari} cm")
print(f"Luas       : {lingkaran1.luas()} cm²")
print(f"Keliling   : {lingkaran1.keliling()} cm")

Jari-jari  : 10 cm
Luas       : 314.159 cm²
Keliling   : 62.8318 cm


**Enkapsulasi - Main Principles of OOP (Hands On)**

bagaimana jika saya ingin mengubah gender "Male" dari user Jonathan menjadi "unknown"???

In [8]:
class User:
    def __init__(self, username, email, gender):
        self._username = username   # Enkapsulasi dengan underscore (_)
        self._email = email
        self._gender = gender

    def get_username(self):
        return self._username

    def set_username(self, username):
        self._username = username

    def get_email(self):
        return self._email

    def set_email(self, email):
        self._email = email

    def get_gender(self):
        return self._gender

    def set_gender(self, gender):
        self._gender = gender

In [12]:
user = User("Jonathan Adis Pratama", "jonathan@example.com", "")

print(user.get_username())  # Mengakses melalui metode getter
user.set_username("Jo saja")  # Mengubah melalui metode setter
print(user.get_username())

print(user.get_gender())        # Mengakses gender melalui getter
user.set_gender("Unknown")      # Mengubah gender melalui setter
print(user.get_gender())        # Menampilkan gender setelah diubah

Jonathan Adis Pratama
Jo saja

Unknown


1. Enkapsulasi digunakan untuk menyembunyikan implementasi internal dan melindungi atribut agar tidak dapat diakses atau diubah secara langsung.
2. Atribut username, email, dan gender diberi awalan _ untuk menandakan bahwa seharusnya diakses secara terbatas.
3. Metode getter get_username digunakan untuk mengakses nilai atribut, dan setter set_username digunakan untuk mengubahnya dengan validasi atau logika tambahan.


**OOP Principles (Hands On)**

Buatlah program yang mengandung 2/3 Main Principles of OOP selain contoh diatas. Lalu presentasikan kedepan satu-satu

In [26]:
from abc import ABC, abstractmethod

# ABSTRACTION - Class abstrak sebagai blueprint
class Karyawan(ABC):
    def __init__(self, nama, departemen):
        self._nama = nama
        self._departemen = departemen

    @abstractmethod
    def hitung_gaji(self):
        pass

    @abstractmethod
    def info_jabatan(self):
        pass

    def info(self):
        print(f"\n{'='*40}")
        print(f"  Nama       : {self._nama}")
        print(f"  Departemen : {self._departemen}")
        print(f"  Jabatan    : {self.info_jabatan()}")
        print(f"  Gaji       : Rp {self.hitung_gaji():,.0f}")
        print(f"{'='*40}")


# INHERITANCE - Subclass mewarisi class Karyawan
class CEO(Karyawan):
    def __init__(self, nama, departemen, tunjangan):
        super().__init__(nama, departemen)
        self.__tunjangan = tunjangan

    # POLYMORPHISM
    def hitung_gaji(self):
        gaji_pokok = 100000000
        return gaji_pokok + self.__tunjangan

    def info_jabatan(self):
        return "CEO"


class VP(Karyawan):
    def __init__(self, nama, departemen, level):
        super().__init__(nama, departemen)
        self.__level = level

    # POLYMORPHISM
    def hitung_gaji(self):
        gaji = {"junior": 15000000, "mid": 30000000, "senior": 60000000}
        return gaji.get(self.__level, 0)

    def info_jabatan(self):
        return f"VP ({self.__level.capitalize()})"


class Programmer(Karyawan):
    def __init__(self, nama, departemen, level):
        super().__init__(nama, departemen)
        self.__level = level

    # POLYMORPHISM
    def hitung_gaji(self):
        gaji = {"junior": 10000000, "mid": 20000000, "senior": 4000000}
        return gaji.get(self.__level, 0)

    def info_jabatan(self):
        return f"Programmer ({self.__level.capitalize()})"


# MAIN - Membuat objek dan menampilkan info
karyawan1 = CEO("Kusuma", "Leader of Company", 00000000)
karyawan2 = VP("Besli", "HRM", "senior")
karyawan3 = Programmer("Syafi", "Senior Dev", "mid")

daftar_karyawan = [karyawan1, karyawan2, karyawan3]

print("\n📋 DATA KARYAWAN PERUSAHAAN")
for karyawan in daftar_karyawan:
    karyawan.info()


📋 DATA KARYAWAN PERUSAHAAN

  Nama       : Kusuma
  Departemen : Leader of Company
  Jabatan    : CEO
  Gaji       : Rp 100,000,000

  Nama       : Besli
  Departemen : HRM
  Jabatan    : VP (Senior)
  Gaji       : Rp 60,000,000

  Nama       : Syafi
  Departemen : Senior Dev
  Jabatan    : Programmer (Mid)
  Gaji       : Rp 20,000,000


1. **Abstraction**

Fungsi: Class Karyawan adalah blueprint (kerangka) yang tidak bisa dibuat objeknya secara langsung. @abstractmethod memaksa setiap subclass untuk wajib mengimplementasikan method hitung_gaji() dan info_jabatan(). Jika tidak diimplementasikan, program akan error.

2. **Inheritance**

Fungsi: Class CEO, VP, dan Programmer mewarisi atribut _nama dan _departemen serta method info() dari class Karyawan melalui super().__init__(). Sehingga tidak perlu menulis ulang kode yang sama di setiap subclass.

3. **Polymorphism**

Fungsi: Method hitung_gaji() dan info_jabatan() dipanggil dengan nama yang sama di semua subclass, tetapi hasilnya berbeda-beda tergantung jenis karyawannya. Ini terlihat jelas saat looping:

